function display1(){
    let element = document.getElementById("place_1");
    element.style.display = "grid";
}
function display2(){
    let element = document.getElementById("place_1");
    element.style.display = "none";
}
function display3(){
    let element = document.getElementById("place_2");
    element.style.display = "grid";
}
function display4(){
    let element = document.getElementById("place_2");
    element.style.display = "none";
}
function display5(){
    let element = document.getElementById("place_3");
    element.style.display = "grid";
}
function display6(){
    let element = document.getElementById("place_3");
    element.style.display = "none";
}
function display7(){
    let element = document.getElementById("place_4");
    element.style.display = "grid";
}
function display8(){
    let element = document.getElementById("place_4");
    element.style.display = "none";
}
function display9(){
    let element = document.getElementById("place_5");
    element.style.display = "grid";
}
function display10(){
    let element = document.getElementById("place_5");
    element.style.display = "none";
}
function display11(){
    let element = document.getElementById("place_6");
    element.style.display = "grid";
}
function display12(){
    let element = document.getElementById("place_6");
    element.style.display = "none";
}
function display13(){
    let element = document.getElementById("place_7");
    element.style.display = "grid";
}
function display14(){
    let element = document.getElementById("place_7");
    element.style.display = "none";
}
function display15(){
    let element = document.getElementById("place_8");
    element.style.display = "grid";
}
function display16(){
    let element = document.getElementById("place_8");
    element.style.display = "none";
}
function display17(){
    let element = document.getElementById("place_9");
    element.style.display = "grid";
}
function display18(){
    let element = document.getElementById("place_9");
    element.style.display = "none";
}
function image_display1(){
    let element1 = document.getElementById("first_div");
    let element2 = document.getElementById("second_div");
    let element3 = document.getElementById("third_div");
    let element4 = document.getElementById("fourth_div");
    element1.style.backgroundColor = "red";
    element1.style.color = "white";
    element2.style.backgroundColor = "#ffffe6";
    element2.style.color = "black";
    element3.style.backgroundColor = "#ffffe6";
    element3.style.color = "black";
    element4.style.backgroundColor = "#ffffe6";
    element4.style.color = "black";
    let content1 = document.getElementById("destination_image_1_1");
    content1.innerHTML = `<p id="destination_image_1_1"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/05+Villa+Kinara_1.jpg"></p>`;
    let content2 = document.getElementById("destination_image_1_1_name");
    content2.textContent = "Villa Kinara";
    let content3 = document.getElementById("destination_image_1_1_place");
    content3.textContent = "Reais Magos, Goa";
    let content4 = document.getElementById("destination_image_1_1_placedetails");
    content4.textContent = "BBQ & Bonfire | 4 Bedrooms";
    let content5 = document.getElementById("destination_image_1_1_cost1");
    content5.textContent = "₹ 61,000";
    let content6 = document.getElementById("destination_image_1_1_cost2");
    content6.textContent = "/night";
    let content7 = document.getElementById("destination_image_1_2");
    content7.innerHTML = `<p id="destination_image_1_2"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/03+Hamptons+Charm_1.jpg"></p>`;
    let content8 = document.getElementById("destination_image_1_2_name");
    content8.textContent = "Haptons Charm";
    let content9 = document.getElementById("destination_image_1_2_place");
    content9.textContent = "Alibaug, Maharastra";
    let content10 = document.getElementById("destination_image_1_2_placedetails");
    content10.textContent = "Proximity To Beach | 5 Bedrooms";
    let content11 = document.getElementById("destination_image_1_2_cost1");
    content11.textContent = "₹ 46,000";
    let content12 = document.getElementById("destination_image_1_2_cost2");
    content12.textContent = "/night";
    let content13 = document.getElementById("destination_image_1_3");
    content13.innerHTML = `<p id="destination_image_1_3"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/02+Umber_1.jpg"></p>`;
    let content14 = document.getElementById("destination_image_1_3_name");
    content14.textContent = "Umber Villa";
    let content15 = document.getElementById("destination_image_1_3_place");
    content15.textContent = "Alibaug, Maharastra";
    let content16 = document.getElementById("destination_image_1_3_placedetails");
    content16.textContent = "Ensuite Jacuzzi | 5 Bedrooms";
    let content17 = document.getElementById("destination_image_1_3_cost1");
    content17.textContent = "₹ 53,250";
    let content18 = document.getElementById("destination_image_1_3_cost2");
    content18.textContent = "/night";
    let content19 = document.getElementById("destination_image_2_1");
    content19.innerHTML = `<p id="destination_image_2_1"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/01+Pranaam_1.jpg"></p>`;
    let content20 = document.getElementById("destination_image_2_1_name");
    content20.textContent = "Pranaam";
    let content21 = document.getElementById("destination_image_2_1_place");
    content21.textContent = "Alibaug, Maharastra";
    let content22 = document.getElementById("destination_image_2_1_placedetails");
    content22.textContent = "Contemporary Interiors | 6 Bedrooms";
    let content23 = document.getElementById("destination_image_2_1_cost1");
    content23.textContent = "₹ 76,000";
    let content24 = document.getElementById("destination_image_2_1_cost2");
    content24.textContent = "/night";
    let content25 = document.getElementById("destination_image_2_2");
    content25.innerHTML = `<p id="destination_image_2_2"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/11+Paashan_1.jpg"></p>`;
    let content26 = document.getElementById("destination_image_2_2_name");
    content26.textContent = "Haptons Charm";
    let content27 = document.getElementById("destination_image_2_2_place");
    content27.textContent = "Khopoli, Maharastra";
    let content28 = document.getElementById("destination_image_2_2_placedetails");
    content28.textContent = "Heated Infinity Pool | 3 Bedrooms";
    let content29 = document.getElementById("destination_image_2_2_cost1");
    content29.textContent = "₹ 66,000";
    let content30 = document.getElementById("destination_image_2_2_cost2");
    content30.textContent = "/night";
    let content31 = document.getElementById("destination_image_2_3");
    content31.innerHTML = `<p id="destination_image_2_3"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/04+The+Rain_1.jpg"></p>`;
    let content32 = document.getElementById("destination_image_2_3_name");
    content32.textContent = "The Rain";
    let content33 = document.getElementById("destination_image_2_3_place");
    content33.textContent = "Alleppey, Kerala";
    let content34 = document.getElementById("destination_image_2_3_placedetails");
    content34.textContent = "Lake View | 4 Bedrooms";
    let content35 = document.getElementById("destination_image_2_3_cost1");
    content35.textContent = "₹ 39,050";
    let content36 = document.getElementById("destination_image_2_3_cost2");
    content36.textContent = "/night";
    let content37 = document.getElementById("destination_image_3_1");
    content37.innerHTML = `<p id="destination_image_3_1"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/06+Ashore_1.jpg"></p>`;
    let content38 = document.getElementById("destination_image_3_1_name");
    content38.textContent = "Ashore";
    let content39 = document.getElementById("destination_image_3_1_place");
    content39.textContent = "Morjim, Goa";
    let content40 = document.getElementById("destination_image_3_1_placedetails");
    content40.textContent = "Infinity Pool | 6 Bedrooms";
    let content41 = document.getElementById("destination_image_3_1_cost1");
    content41.textContent = "₹ 51,000";
    let content42 = document.getElementById("destination_image_3_1_cost2");
    content42.textContent = "/night";
    let content43 = document.getElementById("destination_image_3_2");
    content43.innerHTML = `<p id="destination_image_3_2"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/09+Nayo+Nash_1.jpg"></p>`;
    let content44 = document.getElementById("destination_image_3_2_name");
    content44.textContent = "Nayo Nash";
    let content45 = document.getElementById("destination_image_3_2_place");
    content45.textContent = "Lonavala, Maharastra";
    let content46 = document.getElementById("destination_image_3_2_placedetails");
    content46.textContent = "Lake View | 3 Bedrooms";
    let content47 = document.getElementById("destination_image_3_2_cost1");
    content47.textContent = "₹ 76,000";
    let content48 = document.getElementById("destination_image_3_2_cost2");
    content48.textContent = "/night";
    let content49 = document.getElementById("destination_image_3_3");
    content49.innerHTML = `<p id="destination_image_3_3"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/40+The+Happy+hive_1.jpg"></p>`;
    let content50 = document.getElementById("destination_image_3_3_name");
    content50.textContent = "The Happy Hive";
    let content51 = document.getElementById("destination_image_3_3_place");
    content51.textContent = "Alleppey, Kerala";
    let content52 = document.getElementById("destination_image_3_3_placedetails");
    content52.textContent = "Lake View | 4 Bedrooms";
    let content53 = document.getElementById("destination_image_3_3_cost1");
    content53.textContent = "₹ 39,050";
    let content54 = document.getElementById("destination_image_3_3_cost2");
    content54.textContent = "/night";
}
function image_display2(){
    let element1 = document.getElementById("first_div");
    let element2 = document.getElementById("second_div");
    let element3 = document.getElementById("third_div");
    let element4 = document.getElementById("fourth_div");
    element2.style.backgroundColor = "red";
    element2.style.color = "white";
    element1.style.backgroundColor = "#ffffe6";
    element1.style.color = "black";
    element3.style.backgroundColor = "#ffffe6";
    element3.style.color = "black";
    element4.style.backgroundColor = "#ffffe6";
    element4.style.color = "black";
    let content1 = document.getElementById("destination_image_1_1");
    content1.innerHTML = `<p id="destination_image_1_1"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/40+The+Happy+hive_1.jpg"></p>`;
    let content2 = document.getElementById("destination_image_1_1_name");
    content2.textContent = "The Happy Hive";
    let content3 = document.getElementById("destination_image_1_1_place");
    content3.textContent = "Lonavala, Maharastra";
    let content4 = document.getElementById("destination_image_1_1_placedetails");
    content4.textContent = "Pool & Gazebo | 3 Bedrooms";
    let content5 = document.getElementById("destination_image_1_1_cost1");
    content5.textContent = "₹ 23,500";
    let content6 = document.getElementById("destination_image_1_1_cost2");
    content6.textContent = "/night";
    let content7 = document.getElementById("destination_image_1_2");
    content7.innerHTML = `<p id="destination_image_1_2"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/43+Broken+Banyan_1.jpg"></p>`;
    let content8 = document.getElementById("destination_image_1_2_name");
    content8.textContent = "Broken Banyan";
    let content9 = document.getElementById("destination_image_1_2_place");
    content9.textContent = "Alibaug, Maharastra";
    let content10 = document.getElementById("destination_image_1_2_placedetails");
    content10.textContent = "Pool & Lawn | 3 Bedrooms";
    let content11 = document.getElementById("destination_image_1_2_cost1");
    content11.textContent = "₹ 21,250";
    let content12 = document.getElementById("destination_image_1_2_cost2");
    content12.textContent = "/night";
    let content13 = document.getElementById("destination_image_1_3");
    content13.innerHTML = `<p id="destination_image_1_3"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/02+Umber_1.jpg"></p>`;
    let content14 = document.getElementById("destination_image_1_3_name");
    content14.textContent = "Umber Villa";
    let content15 = document.getElementById("destination_image_1_3_place");
    content15.textContent = "Alibaug,Maharastra";
    let content16 = document.getElementById("destination_image_1_3_placedetails");
    content16.textContent = "Ensuite Jacuzzi | 5 Bedrooms";
    let content17 = document.getElementById("destination_image_1_3_cost1");
    content17.textContent = "₹ 53,250";
    let content18 = document.getElementById("destination_image_1_3_cost2");
    content18.textContent = "/night";
    let content19 = document.getElementById("destination_image_2_1");
    content19.innerHTML = `<p id="destination_image_2_1"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/21+Casa+blanca_1.jpg"></p>`;
    let content20 = document.getElementById("destination_image_2_1_name");
    content20.textContent = "Casa Blanca";
    let content21 = document.getElementById("destination_image_2_1_place");
    content21.textContent = "Karjat, Maharastra";
    let content22 = document.getElementById("destination_image_2_1_placedetails");
    content22.textContent = "Pool & Deck | 4 Bedrooms";
    let content23 = document.getElementById("destination_image_2_1_cost1");
    content23.textContent = "₹ 30,000";
    let content24 = document.getElementById("destination_image_2_1_cost2");
    content24.textContent = "/night";
    let content25 = document.getElementById("destination_image_2_2");
    content25.innerHTML = `<p id="destination_image_2_2"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/26+Nivaant%20farms_1.jpg"></p>`;
    let content26 = document.getElementById("destination_image_2_2_name");
    content26.textContent = "Nivaant farms";
    let content27 = document.getElementById("destination_image_2_2_place");
    content27.textContent = "Karjat, Maharastra";
    let content28 = document.getElementById("destination_image_2_2_placedetails");
    content28.textContent = "Sprawling Lawn | 5 Bedrooms";
    let content29 = document.getElementById("destination_image_2_2_cost1");
    content29.textContent = "₹ 44,000";
    let content30 = document.getElementById("destination_image_2_2_cost2");
    content30.textContent = "/night";
    let content31 = document.getElementById("destination_image_2_3");
    content31.innerHTML = `<p id="destination_image_2_3"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/27+Villa%2041_1.jpg"></p>`;
    let content32 = document.getElementById("destination_image_2_3_name");
    content32.textContent = "Villa 41";
    let content33 = document.getElementById("destination_image_2_3_place");
    content33.textContent = "Lonavala, Maharastra";
    let content34 = document.getElementById("destination_image_2_3_placedetails");
    content34.textContent = "Gaming Zone | 6 Bedrooms";
    let content35 = document.getElementById("destination_image_2_3_cost1");
    content35.textContent = "₹ 52,000";
    let content36 = document.getElementById("destination_image_2_3_cost2");
    content36.textContent = "/night";
    let content37 = document.getElementById("destination_image_3_1");
    content37.innerHTML = `<p id="destination_image_3_1"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/45+El+cottage_1.jpg"></p>`;
    let content38 = document.getElementById("destination_image_3_1_name");
    content38.textContent = "El Cottage";
    let content39 = document.getElementById("destination_image_3_1_place");
    content39.textContent = "Lonavala, Maharastra";
    let content40 = document.getElementById("destination_image_3_1_placedetails");
    content40.textContent = "Eclectic Interiors | 3 Bedrooms";
    let content41 = document.getElementById("destination_image_3_1_cost1");
    content41.textContent = "₹ 21,000";
    let content42 = document.getElementById("destination_image_3_1_cost2");
    content42.textContent = "/night";
    let content43 = document.getElementById("destination_image_3_2");
    content43.innerHTML = `<p id="destination_image_3_2"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/35+Villa+Meer_1.jpg"></p>`;
    let content44 = document.getElementById("destination_image_3_2_name");
    content44.textContent = "Villa Meer";
    let content45 = document.getElementById("destination_image_3_2_place");
    content45.textContent = "Nashik, Maharastra";
    let content46 = document.getElementById("destination_image_3_2_placedetails");
    content46.textContent = "Picturesque View | 6 Bedrooms";
    let content47 = document.getElementById("destination_image_3_2_cost1");
    content47.textContent = "₹ 46,000";
    let content48 = document.getElementById("destination_image_3_2_cost2");
    content48.textContent = "/night";
    let content49 = document.getElementById("destination_image_3_3");
    content49.innerHTML = `<p id="destination_image_3_3"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/30+The+Beach+house_1.jpg"></p>`;
    let content50 = document.getElementById("destination_image_3_3_name");
    content50.textContent = "The Beach House";
    let content51 = document.getElementById("destination_image_3_3_place");
    content51.textContent = "Alibaug, Maharastra";
    let content52 = document.getElementById("destination_image_3_3_placedetails");
    content52.textContent = "Proximity To Beach | 3 Bedrooms";
    let content53 = document.getElementById("destination_image_3_3_cost1");
    content53.textContent = "₹ 34,000";
    let content54 = document.getElementById("destination_image_3_3_cost2");
    content54.textContent = "/night";
}
function image_display3(){
    let element1 = document.getElementById("first_div");
    let element2 = document.getElementById("second_div");
    let element3 = document.getElementById("third_div");
    let element4 = document.getElementById("fourth_div");
    element3.style.backgroundColor = "red";
    element3.style.color = "white";
    element2.style.backgroundColor = "#ffffe6";
    element2.style.color = "black";
    element1.style.backgroundColor = "#ffffe6";
    element1.style.color = "black";
    element4.style.backgroundColor = "#ffffe6";
    element4.style.color = "black";
    let content1 = document.getElementById("destination_image_1_1");
    content1.innerHTML = `<p id="destination_image_1_1"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/28+El+house_1.jpg"></p>`;
    let content2 = document.getElementById("destination_image_1_1_name");
    content2.textContent = "El House";
    let content3 = document.getElementById("destination_image_1_1_place");
    content3.textContent = "Kasauli, Himachal Pradesh";
    let content4 = document.getElementById("destination_image_1_1_placedetails");
    content4.textContent = "French Interiors | 3 Bedrooms";
    let content5 = document.getElementById("destination_image_1_1_cost1");
    content5.textContent = "₹ 24,000";
    let content6 = document.getElementById("destination_image_1_1_cost2");
    content6.textContent = "/night";
    let content7 = document.getElementById("destination_image_1_2");
    content7.innerHTML = `<p id="destination_image_1_2"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/22+Neverland+Farms_1.jpg"></p>`;
    let content8 = document.getElementById("destination_image_1_2_name");
    content8.textContent = "Neverland Farms";
    let content9 = document.getElementById("destination_image_1_2_place");
    content9.textContent = "Dehradun, Uttarakhand";
    let content10 = document.getElementById("destination_image_1_2_placedetails");
    content10.textContent = "Eclectic Interiors | 4 Bedrooms";
    let content11 = document.getElementById("destination_image_1_2_cost1");
    content11.textContent = "₹ 31,000";
    let content12 = document.getElementById("destination_image_1_2_cost2");
    content12.textContent = "/night";
    let content13 = document.getElementById("destination_image_1_3");
    content13.innerHTML = `<p id="destination_image_1_3"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/16+Kay+villa_1.jpg"></p>`;
    let content14 = document.getElementById("destination_image_1_3_name");
    content14.textContent = "Kay Villa";
    let content15 = document.getElementById("destination_image_1_3_place");
    content15.textContent = "Sohna, Haryana";
    let content16 = document.getElementById("destination_image_1_3_placedetails");
    content16.textContent = "18th Century Architecture | 6 Bedrooms";
    let content17 = document.getElementById("destination_image_1_3_cost1");
    content17.textContent = "₹ 37,000";
    let content18 = document.getElementById("destination_image_1_3_cost2");
    content18.textContent = "/night";
    let content19 = document.getElementById("destination_image_2_1");
    content19.innerHTML = `<p id="destination_image_2_1"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/13+Aurus+grande_1.jpg"></p>`;
    let content20 = document.getElementById("destination_image_2_1_name");
    content20.textContent = "Auras Grande";
    let content21 = document.getElementById("destination_image_2_1_place");
    content21.textContent = "Chandigarh, Chandigarh";
    let content22 = document.getElementById("destination_image_2_1_placedetails");
    content22.textContent = "Sprawling Lawn | 5 Bedrooms";
    let content23 = document.getElementById("destination_image_2_1_cost1");
    content23.textContent = "₹ 39,000";
    let content24 = document.getElementById("destination_image_2_1_cost2");
    content24.textContent = "/night";
    let content25 = document.getElementById("destination_image_2_2");
    content25.innerHTML = `<p id="destination_image_2_2"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/36+Ananda%20villa_1.jpg"></p>`;
    let content26 = document.getElementById("destination_image_2_2_name");
    content26.textContent = "Ananda Villa";
    let content27 = document.getElementById("destination_image_2_2_place");
    content27.textContent = "Kasauli, Himachal Pradesh";
    let content28 = document.getElementById("destination_image_2_2_placedetails");
    content28.textContent = "Picturesque View | 3 Bedrooms";
    let content29 = document.getElementById("destination_image_2_2_cost1");
    content29.textContent = "₹ 25,000";
    let content30 = document.getElementById("destination_image_2_2_cost2");
    content30.textContent = "/night";
    let content31 = document.getElementById("destination_image_2_3");
    content31.innerHTML = `<p id="destination_image_2_3"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/38+Ayukutir+health+resort_1.jpg"></p>`;
    let content32 = document.getElementById("destination_image_2_3_name");
    content32.textContent = "Ayukutir Health Resort";
    let content33 = document.getElementById("destination_image_2_3_place");
    content33.textContent = "Nainital, Uttarakhand";
    let content34 = document.getElementById("destination_image_2_3_placedetails");
    content34.textContent = "Serene Location | 5 Bedrooms";
    let content35 = document.getElementById("destination_image_2_3_cost1");
    content35.textContent = "₹ 21,000";
    let content36 = document.getElementById("destination_image_2_3_cost2");
    content36.textContent = "/night";
    let content37 = document.getElementById("destination_image_3_1");
    content37.innerHTML = `<p id="destination_image_3_1"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/46+Villa+Ashirvad_1.jpg"></p>`;
    let content38 = document.getElementById("destination_image_3_1_name");
    content38.textContent = "Villa Ashirvad";
    let content39 = document.getElementById("destination_image_3_1_place");
    content39.textContent = "Udaipur, Rajasthan";
    let content40 = document.getElementById("destination_image_3_1_placedetails");
    content40.textContent = "Picturesque View | 4 Bedrooms";
    let content41 = document.getElementById("destination_image_3_1_cost1");
    content41.textContent = "₹ 37,000";
    let content42 = document.getElementById("destination_image_3_1_cost2");
    content42.textContent = "/night";
    let content43 = document.getElementById("destination_image_3_2");
    content43.innerHTML = `<p id="destination_image_3_2"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/29+Glass+house_1.jpg"></p>`;
    let content44 = document.getElementById("destination_image_3_2_name");
    content44.textContent = "Glass House";
    let content45 = document.getElementById("destination_image_3_2_place");
    content45.textContent = "New Delhi, Delhi";
    let content46 = document.getElementById("destination_image_3_2_placedetails");
    content46.textContent = "Amphitheatre | 4 Bedrooms";
    let content47 = document.getElementById("destination_image_3_2_cost1");
    content47.textContent = "₹ 30,750";
    let content48 = document.getElementById("destination_image_3_2_cost2");
    content48.textContent = "/night";
    let content49 = document.getElementById("destination_image_3_3");
    content49.innerHTML = `<p id="destination_image_3_3"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/24+Acacia+Villa_1.jpg"></p>`;
    let content50 = document.getElementById("destination_image_3_3_name");
    content50.textContent = "Acacia Villa";
    let content51 = document.getElementById("destination_image_3_3_place");
    content51.textContent = "Dehradun, Uttarakhand";
    let content52 = document.getElementById("destination_image_3_3_placedetails");
    content52.textContent = "Sprawling Orchards | 3 Bedrooms";
    let content53 = document.getElementById("destination_image_3_3_cost1");
    content53.textContent = "₹ 25,500";
    let content54 = document.getElementById("destination_image_3_3_cost2");
    content54.textContent = "/night";
}
function image_display4(){
    let element1 = document.getElementById("first_div");
    let element2 = document.getElementById("second_div");
    let element3 = document.getElementById("third_div");
    let element4 = document.getElementById("fourth_div");
    element4.style.backgroundColor = "red";
    element4.style.color = "white";
    element2.style.backgroundColor = "#ffffe6";
    element2.style.color = "black";
    element3.style.backgroundColor = "#ffffe6";
    element3.style.color = "black";
    element1.style.backgroundColor = "#ffffe6";
    element1.style.color = "black";
    let content1 = document.getElementById("destination_image_1_1");
    content1.innerHTML = `<p id="destination_image_1_1"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/50+Cheppanam+House_1.jpg"></p>`;
    let content2 = document.getElementById("destination_image_1_1_name");
    content2.textContent = "Cheppanam House";
    let content3 = document.getElementById("destination_image_1_1_place");
    content3.textContent = "Ernakulam, Kerala";
    let content4 = document.getElementById("destination_image_1_1_placedetails");
    content4.textContent = "Serene Location | 3 Bedrooms";
    let content5 = document.getElementById("destination_image_1_1_cost1");
    content5.textContent = "₹ 17,500";
    let content6 = document.getElementById("destination_image_1_1_cost2");
    content6.textContent = "/night";
    let content7 = document.getElementById("destination_image_1_2");
    content7.innerHTML = `<p id="destination_image_1_2"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/56+Dwarka+inn_1.jpg"></p>`;
    let content8 = document.getElementById("destination_image_1_2_name");
    content8.textContent = "Dwarka Inn";
    let content9 = document.getElementById("destination_image_1_2_place");
    content9.textContent = "Coimbatore, Tamil Nadu";
    let content10 = document.getElementById("destination_image_1_2_placedetails");
    content10.textContent = "Swimming Pool | 6 Bedrooms";
    let content11 = document.getElementById("destination_image_1_2_cost1");
    content11.textContent = "₹ 33,000";
    let content12 = document.getElementById("destination_image_1_2_cost2");
    content12.textContent = "/night";
    let content13 = document.getElementById("destination_image_1_3");
    content13.innerHTML = `<p id="destination_image_1_3"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/55+Toya+toya_1.jpg"></p>`;
    let content14 = document.getElementById("destination_image_1_3_name");
    content14.textContent = "Toya Toya";
    let content15 = document.getElementById("destination_image_1_3_place");
    content15.textContent = "Kozhikode, Kerala";
    let content16 = document.getElementById("destination_image_1_3_placedetails");
    content16.textContent = "Jacuzzi | 3 Bedrooms";
    let content17 = document.getElementById("destination_image_1_3_cost1");
    content17.textContent = "₹ 21,000";
    let content18 = document.getElementById("destination_image_1_3_cost2");
    content18.textContent = "/night";
    let content19 = document.getElementById("destination_image_2_1");
    content19.innerHTML = `<p id="destination_image_2_1"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/54+Shalom+villa_1.jpg"></p>`;
    let content20 = document.getElementById("destination_image_2_1_name");
    content20.textContent = "Shalom Villa";
    let content21 = document.getElementById("destination_image_2_1_place");
    content21.textContent = "Allepey, Kerala";
    let content22 = document.getElementById("destination_image_2_1_placedetails");
    content22.textContent = "Royal Decor | 4 Bedrooms";
    let content23 = document.getElementById("destination_image_2_1_cost1");
    content23.textContent = "₹ 28,000";
    let content24 = document.getElementById("destination_image_2_1_cost2");
    content24.textContent = "/night";
    let content25 = document.getElementById("destination_image_2_2");
    content25.innerHTML = `<p id="destination_image_2_2"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/53++Talerock+Inn_1.jpg"></p>`;
    let content26 = document.getElementById("destination_image_2_2_name");
    content26.textContent = "Telerock Inn";
    let content27 = document.getElementById("destination_image_2_2_place");
    content27.textContent = "Valparai, Tamil Nadu";
    let content28 = document.getElementById("destination_image_2_2_placedetails");
    content28.textContent = "Serene Location | 3 Bedrooms";
    let content29 = document.getElementById("destination_image_2_2_cost1");
    content29.textContent = "₹ 44,500";
    let content30 = document.getElementById("destination_image_2_2_cost2");
    content30.textContent = "/night";
    let content31 = document.getElementById("destination_image_2_3");
    content31.innerHTML = `<p id="destination_image_2_3"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/52+Silver+Mist_1.jpg"></p>`;
    let content32 = document.getElementById("destination_image_2_3_name");
    content32.textContent = "Silver Mist";
    let content33 = document.getElementById("destination_image_2_3_place");
    content33.textContent = "Ooty, Tamil Nadu";
    let content34 = document.getElementById("destination_image_2_3_placedetails");
    content34.textContent = "Library & Games | 3 Bedrooms";
    let content35 = document.getElementById("destination_image_2_3_cost1");
    content35.textContent = "₹ 17,500";
    let content36 = document.getElementById("destination_image_2_3_cost2");
    content36.textContent = "/night";
    let content37 = document.getElementById("destination_image_3_1");
    content37.innerHTML = `<p id="destination_image_3_1"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/51+Mynaakom_1.jpg"></p>`;
    let content38 = document.getElementById("destination_image_3_1_name");
    content38.textContent = "Mynaakom";
    let content39 = document.getElementById("destination_image_3_1_place");
    content39.textContent = "Thekkady, Karnataka";
    let content40 = document.getElementById("destination_image_3_1_placedetails");
    content40.textContent = "Gazebo & Views | 3 Bedrooms";
    let content41 = document.getElementById("destination_image_3_1_cost1");
    content41.textContent = "₹ 19,400";
    let content42 = document.getElementById("destination_image_3_1_cost2");
    content42.textContent = "/night";
    let content43 = document.getElementById("destination_image_3_2");
    content43.innerHTML = `<p id="destination_image_3_2"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/37+Springhills+villa+_+ayurvedic+Spa_1.jpg"></p>`;
    let content44 = document.getElementById("destination_image_3_2_name");
    content44.textContent = "Springhills Villa & Ayurvedic Spa";
    let content45 = document.getElementById("destination_image_3_2_place");
    content45.textContent = "Kochi, Kerala";
    let content46 = document.getElementById("destination_image_3_2_placedetails");
    content46.textContent = "Ayurvedic Spa | 6 Bedrooms";
    let content47 = document.getElementById("destination_image_3_2_cost1");
    content47.textContent = "₹ 19,000";
    let content48 = document.getElementById("destination_image_3_2_cost2");
    content48.textContent = "/night";
    let content49 = document.getElementById("destination_image_3_3");
    content49.innerHTML = `<p id="destination_image_3_3"><img src="https://img.vistarooms.com/angular_assets/common/static_prop/24+Acacia+Villa_1.jpg"></p>`;
    let content50 = document.getElementById("destination_image_3_3_name");
    content50.textContent = "Tail Silver";
    let content51 = document.getElementById("destination_image_3_3_place");
    content51.textContent = "Coorg, Karnataka";
    let content52 = document.getElementById("destination_image_3_3_placedetails");
    content52.textContent = "Swimming Pool | 2 Bedrooms";
    let content53 = document.getElementById("destination_image_3_3_cost1");
    content53.textContent = "₹ 16,000";
    let content54 = document.getElementById("destination_image_3_3_cost2");
    content54.textContent = "/night";
}